---
  #Passing --pod-network-cidr option to kubeadm init is not required, but highly recommended.
  #
  #These commands will deploy Cilium with its own etcd managed by etcd operator.
  #
  ## Download required manifests from Cilium repository
  #wget https://github.com/cilium/cilium/archive/v1.2.0.zip
  #unzip v1.2.0.zip
  #cd cilium-1.2.0/examples/kubernetes/addons/etcd-operator
  #
  ## Generate and deploy etcd certificates
  #export CLUSTER_DOMAIN=$(kubectl get ConfigMap --namespace kube-system coredns -o yaml | awk '/kubernetes/ {print $2}')
  #tls/certs/gen-cert.sh $CLUSTER_DOMAIN
  #tls/deploy-certs.sh
  #
  ## Label kube-dns with fixed identity label
  #kubectl label -n kube-system pod $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[]}{.metadata.name}{" "}{end}') io.cilium.fixed-identity=kube-dns
  #
  #kubectl create -f ./

# Upgrading kernel is needed since we are on 4.4
- name: Get new kernel
  get_url:
    url: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.18.7/linux-image-4.18.7-041807-generic_4.18.7-041807.201809090930_i386.deb 
    dest: /tmp/kernel.deb
  when: ubuntu_kernel

- name: Install new kernel
  apt:
    deb: /tmp/kernel.deb
  when: ubuntu_kernel

- name: Reload the boxes for new kernel
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: ubuntu_kernel

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: ubuntu_kernel

- name: Mount bpffs
  mount:
    path: /sys/fs/bpf
    src: bpffs
    fstype: bpf
    state: mounted

- name: Copy cilium archive to use etcd operator
  get_url:
    url: https://github.com/cilium/cilium/archive/v1.2.1.zip 
    dest: /tmp/
  delegate_to: "{{ groups['masters'][0] }}"

- name: Install packages dependencies
  apt:
    name: "{{ item }}"
    state: present
  with:
    - unzip

- name: Install cilium scripts dependencies
  get_url: 
    url: "https://pkg.cfssl.org/R1.2/{{ item }}_linux-amd64"
    dest: "/usr/local/bin/{{ item }}"
    mode: 755
  with:
    - cfssl
    - cfssljson

- name: Unarchive
  unarchive:
    src: /tmp/cilium-1.2.1.zip
    dest: /tmp/
    remote_src: yes
  delegate_to: "{{ groups['masters'][0] }}"

- name: gen tls
  shell: /tmp/cilium-1.2.1/examples/kubernetes/addons/etcd-operator/tls/certs/gen-cert.sh cluster.local
  delegate_to: "{{ groups['masters'][0] }}"

- name: deploy certs
  shell: /tmp/cilium-1.2.1/examples/kubernetes/addons/etcd-operator/tls/deploy-certs.sh
  delegate_to: "{{ groups['masters'][0] }}"

- name: Label dns pod for cilium
  shell: kubectl label -n kube-system pod $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[]}{.metadata.name}{" "}{end}') io.cilium.fixed-identity=kube-dns
  delegate_to: "{{ groups['masters'][0] }}"

- name: deploy etcd for cilium
  shell: kubectl create -f /tmp/cilium-1.2.1/examples/kubernetes/addons/etcd-operator/
  delegate_to: "{{ groups['masters'][0] }}"

- name: Copy cilium.yaml file
  template: 
    src: cilium.j2
    dest: /tmp/cilium.yaml
  delegate_to: "{{ groups['masters'][0] }}"

- name: Adding Cilium
  shell: "kubectl apply -f /tmp/cilium.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
