---
- name: Get keys of kube repo  
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kube prequisites
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - docker.io
    - rsync
    - python-apt
    - python3-apt

- name: Wget prequisites froom google storage
  get_url:
    url: "{{ item }}"
    dest: /tmp/
  with_items: 
    - "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_release }}/bin/linux/amd64/kubectl"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_release }}/bin/linux/amd64/kubeadm"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_release }}/bin/linux/amd64/kubelet"
    - "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ k8s_release }}/build/debs/kubelet.service"
    - "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ k8s_release }}/build/debs/10-kubeadm.conf"
    - "https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-amd64-{{ cni_version }}.tgz"
    - "https://storage.googleapis.com/kubernetes-the-hard-way/kube-dns.yaml"
  tags: pre

- name: Creating missing directories
  file: 
    path="{{ item }}"
    state=directory
  with_items:
    - /etc/systemd/system/kubelet.service.d/
    - /opt/cni/bin

- name: Copying admin files to bin
  copy:
    src: "/tmp/{{ item }}"
    dest: /usr/bin/
    mode: "u+x"
    remote_src: yes
  with_items:
    - kubeadm
    - kubectl
    - kubelet

- name: Untaring & moving cni files
  unarchive:
    src: "/tmp/cni-plugins-amd64-{{ cni_version }}.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes

- name: Copying kubeadm service file
  copy:
    src: "/tmp/{{ item }}"
    dest: /etc/systemd/system/kubelet.service.d/
    mode: "u+x"
    remote_src: yes
  with_items:
    - 10-kubeadm.conf

- name: Copying kubelet service file
  copy:
    src: "/tmp/{{ item }}"
    dest: /etc/systemd/system/
    mode: "u+x"
    remote_src: yes
  with_items:
    - kubelet.service

- name: daemon reload
  systemd: 
    daemon_reload: yes

- name: Start services
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - kubelet