---
# Global variables that can 
# be included in a task with 
#  include_vars: "{{ playbook_dir }}/config.yaml"
################################################

#
## Global envs ##
#
k8s_release: v1.11.1
cni_version: v0.7.0 # This is the real release version of the cni plugins
cni_config_version: 0.3.1 # This version is needed in the bridges/ipvlan/etc config files
kubeadm_token: 7cb4a1.df899180a95cc374
phases: simple # Or 'custom' to use customized phases (and the variables related)
#
# WARNING !!!!
# Some solutions (like calico) have some constraints on the adressing scheme without tweaking the yaml :
# https://kubernetes.io/docs/concepts/cluster-administration/addons/
# (cluster cidr should be 192.168.0.0/16 for example)
# I will assume here that you are aware of this (at least for now)
calico_yaml: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml
calicoctl_yaml: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/calicoctl.yaml
#
## Essential network variables ##
#
simple_cni_solution: true # If it is a default solution from the cni project (like bridge or ipvlan)
network_solution: cilium # could be any cni (ex: bridge, ipvlan, ..) or addons (calico, flannel,...)
# For a cni solution, there are templates in the "join" role. You can tweak them if you want/need
master_ip: 11.11.11.11  # Also known as API Endpoint or apiserver IP
master_port: 6443  # Also known as API Endpoint or apiserver Port
service_ip: 85.85.0.0/16 # Why 85 ? Because it looks like 8s in k8s ;-)
cluster_dns: 85.85.85.85  
cluster_cidr: 172.16.0.0/16
coredns: false # If false, will use kubedns as a default
#
## Some cookies on top of the icecream
#
istio: false # Adding Istio at the end of the install
istio_version: v0.6.0
istio_auth: false # true will enable TLS between istio components (and use istio-auth.yaml instead)
auto_sidecar_inject: true # WARNING : needs a k8s version of at least 1.9
